const mockProductData = [
  {
    id: 1,
    name: "Fidget Spinner",
    description: "Entspannender Fidget Spinner für Stressabbau.",
    price: 5.99,
    inStockCount: 100,
    imgMain: "/img/products/fidget_spinner.jpg",
    imgOther: [""],
    category: "Toys",
  },
  {
    id: 2,
    name: "Smartwatch",
    description:
      "Moderne Smartwatch mit Herzfrequenzmesser und Fitness-Tracking.",
    price: 149.99,
    inStockCount: 35,
    imgMain: "/img/products/smartwatch.jpg",
    imgOther: [""],
    category: "Electronics",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    description: "Kabelloser Bluetooth-Lautsprecher mit sattem Klang.",
    price: 29.99,
    inStockCount: 60,
    imgMain: "/img/products/bluetooth_speaker.jpg",
    imgOther: [""],
    category: "Electronics",
  },
  {
    id: 4,
    name: "Wireless Earbuds",
    description: "Kabellose In-Ear-Kopfhörer mit Geräuschunterdrückung.",
    price: 89.99,
    inStockCount: 25,
    imgMain: "/img/products/wireless_earbuds.jpg",
    imgOther: [""],
    category: "Electronics",
  },
  {
    id: 5,
    name: "Gaming Mouse",
    description: "Ergonomische Gaming-Maus mit RGB-Beleuchtung.",
    price: 49.99,
    inStockCount: 20,
    imgMain: "/img/products/gaming_mouse.jpg",
    imgOther: [""],
    category: "Gaming",
  },
  {
    id: 6,
    name: "Hoverboard",
    description: "Modernes Hoverboard mit LED-Beleuchtung und Bluetooth.",
    price: 199.99,
    inStockCount: 10,
    imgMain: "/img/products/hoverboard.jpg",
    imgOther: [""],
    category: "Toys",
  },
  {
    id: 7,
    name: "Powerbank 10.000mAh",
    description:
      "Leistungsstarke Powerbank für unterwegs, ideal zum Aufladen deines Smartphones.",
    price: 19.99,
    inStockCount: 80,
    imgMain: "/img/products/powerbank.jpg",
    imgOther: [""],
    category: "Electronics",
  },
  {
    id: 8,
    name: "Selfie Stick",
    description: "Verstellbarer Selfie-Stick mit Bluetooth-Auslöser.",
    price: 9.99,
    inStockCount: 120,
    imgMain: "/img/products/selfie_stick.jpg",
    imgOther: [""],
    category: "Accessories",
  },
  {
    id: 9,
    name: "LED Ring Light",
    description:
      "Professionelles LED-Ringlicht für perfekte Selfies und Videos.",
    price: 39.99,
    inStockCount: 15,
    imgMain: "/img/products/led_ring_light.jpg",
    imgOther: [""],
    category: "Electronics",
  },
];

export default mockProductData;
